services:
  nginx:
    build:
      context: .
      dockerfile: environment/dev/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - connection
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: environment/dev/php/Dockerfile
    container_name: php
    networks:
      - connection
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: cn-project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - nc-db:/var/lib/mysql
    networks:
      - connection

volumes:
  nc-db:

networks:
  connection:
    driver: bridge
