services:
    php:
        build:
            context: .
            dockerfile: /environment/dev/php/Dockerfile
        container_name: php-container
        working_dir: /var/www
        volumes:
            - ./:/var/www
        expose:
            - "9000:9000"
        networks:
            - cn-network
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8.0
        container_name: mysql-container
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=app_db
            - MYSQL_ROOT_PASSWORD=p2ssw0rd
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - cn-network

    nginx:
        image: nginx:latest
        container_name: nginx-container
        ports:
            - "80:80"
        volumes:
            - ./environment/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./:/var/www
        networks:
            - cn-network
        depends_on:
            - php

    redis:
        image: redis:alpine
        container_name: redis-container
        command: redis-server --appendonly yes
        ports:
            - "6379:6379"
        networks:
            - cn-network

volumes:
    db-data:

networks:
    cn-network:
        driver: bridge
